plugins {
    id 'com.android.application'
}

android {
    namespace 'de.mathis.kanban'
    compileSdk 34

    defaultConfig {
        applicationId 'de.mathis.kanban'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        fixed {
            storeFile file('kanban.keystore')
            storePassword 'kanban123'
            keyAlias 'kanban'
            keyPassword 'kanban123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.fixed
        }
        debug {
            signingConfig signingConfigs.fixed
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
